#!/usr/bin/env bash
# One-shot host gateway so Cursor Remote-SSH → Host `ajos` works.
#
# cursor-server cannot run inside AJOS (32-bit hobby kernel, no Linux
# userspace). This script:
#   1. sshfs-mounts the guest VFS (user@127.0.0.1:9022)
#   2. Starts a *host* OpenSSH listener on 127.0.0.1:22229 (no root)
#   3. Writes an SSH config snippet: Host ajos  →  that listener
#   4. Installs Cursor/VS Code terminal profiles that SSH into the guest
#
# Prerequisites: OpenSSH client, sshfs (macFUSE on macOS), sshpass (or you
# will be prompted for the guest password `pass`), and a running AJOS guest
# (`make run-console-file`).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

HOST="${AJOS_SSH_HOST:-127.0.0.1}"
GUEST_PORT="${HOST_SSH_PORT:-9022}"
GUEST_USER="${AJOS_SSH_USER:-user}"
GUEST_PASS="${AJOS_SSH_PASSWORD:-pass}"
GW_PORT="${AJOS_GATEWAY_PORT:-22229}"
STATE="${AJOS_CURSOR_REMOTE_DIR:-${HOME}/.ajos-cursor-remote}"
MNT="${STATE}/mnt"
HOST_USER="$(id -un)"
HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: missing '$1'. $2" >&2
    exit 1
  fi
}

need ssh "Install OpenSSH client."
need ssh-keygen "Install OpenSSH client."
need sshd "Install OpenSSH server (Linux: openssh-server; macOS: enable Remote Login or use the sshd in /usr/sbin)."

if ! command -v sshfs >/dev/null 2>&1; then
  echo "error: sshfs not found." >&2
  echo "  Linux:  sudo apt install sshfs   (or dnf/pacman equivalent)" >&2
  echo "  macOS:  brew install macfuse && brew install gromgit/fuse/sshfs-mac" >&2
  exit 1
fi

mkdir -p "${STATE}" "${MNT}"
chmod 700 "${STATE}"

# --- keys (generated locally; never committed) ---
if [ ! -f "${STATE}/id_ed25519" ]; then
  ssh-keygen -t ed25519 -N "" -f "${STATE}/id_ed25519" -C "ajos-cursor-gateway" >/dev/null
fi
if [ ! -f "${STATE}/ssh_host_ed25519_key" ]; then
  ssh-keygen -t ed25519 -N "" -f "${STATE}/ssh_host_ed25519_key" -C "ajos-gateway-host" >/dev/null
fi
cp -f "${STATE}/id_ed25519.pub" "${STATE}/authorized_keys"
chmod 600 "${STATE}/id_ed25519" "${STATE}/ssh_host_ed25519_key" "${STATE}/authorized_keys"

# --- sshd_config (user-mode, loopback only) ---
cat > "${STATE}/sshd_config" <<EOF
Port ${GW_PORT}
ListenAddress 127.0.0.1
Protocol 2
HostKey ${STATE}/ssh_host_ed25519_key
PidFile ${STATE}/sshd.pid
AuthorizedKeysFile ${STATE}/authorized_keys
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
PermitRootLogin no
AllowUsers ${HOST_USER}
UsePAM no
StrictModes no
PrintMotd no
AcceptEnv LANG LC_*
AllowTcpForwarding yes
PermitTunnel no
X11Forwarding no
Subsystem sftp internal-sftp
EOF

# --- Host ajos snippet (Include from ~/.ssh/config) ---
cat > "${STATE}/ssh_config" <<EOF
# Generated by tools/ajos-cursor-remote/setup.sh — not a secret, just a test key.
# Add to ~/.ssh/config:
#   Include ${STATE}/ssh_config
#
Host ajos
    HostName 127.0.0.1
    Port ${GW_PORT}
    User ${HOST_USER}
    IdentityFile ${STATE}/id_ed25519
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ${STATE}/known_hosts
    ServerAliveInterval 15
    ServerAliveCountMax 4
    ForwardAgent no
EOF

# Point Cursor at this file even if the user has not Included it yet.
export CURSOR_SSH_CONFIG="${STATE}/ssh_config"

# --- guest SSH wrapper used by the integrated terminal ---
GUEST_SSH="${STATE}/guest-ssh.sh"
{
  echo "#!/usr/bin/env bash"
  echo "export AJOS_SSH_HOST='${HOST}'"
  echo "export HOST_SSH_PORT='${GUEST_PORT}'"
  echo "export AJOS_SSH_USER='${GUEST_USER}'"
  echo "export AJOS_SSH_PASSWORD='${GUEST_PASS}'"
  echo "exec '${SCRIPT_DIR}/guest-ssh.sh' \"\$@\""
} > "${GUEST_SSH}"
chmod +x "${GUEST_SSH}" "${SCRIPT_DIR}/guest-ssh.sh" "${SCRIPT_DIR}/stop.sh"

# --- Cursor / VS Code remote machine settings (terminal = guest shell) ---
python3 - "${STATE}/cursor-machine-settings.json" "${GUEST_SSH}" "${MNT}" <<'PY'
import json, sys
out, guest_ssh, mnt = sys.argv[1], sys.argv[2], sys.argv[3]
profile = {"path": guest_ssh, "args": []}
settings = {
    "terminal.integrated.defaultProfile.linux": "AJOS Guest",
    "terminal.integrated.defaultProfile.osx": "AJOS Guest",
    "terminal.integrated.profiles.linux": {
        "AJOS Guest": profile,
        "Host shell": {"path": "bash", "args": ["-l"]},
    },
    "terminal.integrated.profiles.osx": {
        "AJOS Guest": profile,
        "Host shell": {"path": "zsh", "args": ["-l"]},
    },
    "terminal.integrated.cwd": mnt,
    "remote.SSH.enableRemoteCommand": False,
}
with open(out, "w", encoding="utf-8") as f:
    json.dump(settings, f, indent=2)
    f.write("\n")
PY

merge_machine_settings() {
  local dest="$1"
  mkdir -p "$(dirname "${dest}")"
  python3 - "${STATE}/cursor-machine-settings.json" "${dest}" <<'PY'
import json, os, sys
src, dest = sys.argv[1], sys.argv[2]
with open(src, encoding="utf-8") as f:
    extra = json.load(f)
cur = {}
if os.path.exists(dest):
    try:
        with open(dest, encoding="utf-8") as f:
            cur = json.load(f)
    except json.JSONDecodeError:
        cur = {}
cur.update(extra)
with open(dest, "w", encoding="utf-8") as f:
    json.dump(cur, f, indent=2)
    f.write("\n")
PY
}

for base in \
  "${HOME}/.cursor-server/data/Machine/settings.json" \
  "${HOME}/.vscode-server/data/Machine/settings.json"
do
  merge_machine_settings "${base}"
done

# Workspace file on the *host* (native FS). Do not put cursor-server on sshfs.
cat > "${STATE}/ajos.code-workspace" <<EOF
{
  "folders": [{ "name": "AJOS VFS", "path": "${MNT}" }],
  "settings": $(python3 -c "import json; print(json.dumps(json.load(open('${STATE}/cursor-machine-settings.json'))))")
}
EOF

# --- wait for guest SSH ---
echo "Checking AJOS guest SSH at ${HOST}:${GUEST_PORT} ..."
guest_up=0
for i in 1 2 3 4 5 6 7 8 9 10; do
  if command -v sshpass >/dev/null 2>&1; then
    if sshpass -p "${GUEST_PASS}" ssh \
         -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
         -o PreferredAuthentications=password -o PubkeyAuthentication=no \
         -o ConnectTimeout=3 -p "${GUEST_PORT}" \
         "${GUEST_USER}@${HOST}" "echo ok" >/dev/null 2>&1; then
      guest_up=1
      break
    fi
  else
    if ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
         -o ConnectTimeout=3 -p "${GUEST_PORT}" \
         "${GUEST_USER}@${HOST}" true >/dev/null 2>&1; then
      guest_up=1
      break
    fi
  fi
  sleep 1
done
if [ "${guest_up}" -ne 1 ]; then
  echo "error: cannot SSH to ${GUEST_USER}@${HOST}:${GUEST_PORT}." >&2
  echo "  Start the guest first:  make run-console-file" >&2
  echo "  Wait for: [SSHD] Server started on port 22" >&2
  echo "  Account: ${GUEST_USER} / ${GUEST_PASS}" >&2
  exit 1
fi

# --- sshfs ---
already_mounted=0
if mount | grep -F " ${MNT} " >/dev/null 2>&1; then
  already_mounted=1
fi
if [ "${already_mounted}" -eq 0 ]; then
  echo "Mounting sshfs ${GUEST_USER}@${HOST}:${GUEST_PORT} -> ${MNT}"
  SSHFS_OPTS="reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,StrictHostKeyChecking=no,UserKnownHostsFile=/dev/null,port=${GUEST_PORT},uid=${HOST_UID},gid=${HOST_GID},idmap=user,cache=yes,entry_timeout=1,attr_timeout=1,max_read=8192,max_write=16384,PasswordAuthentication=yes,PubkeyAuthentication=no"
  if command -v sshpass >/dev/null 2>&1; then
    echo "${GUEST_PASS}" | sshfs -o "${SSHFS_OPTS},password_stdin" \
      "${GUEST_USER}@${HOST}:/" "${MNT}"
  else
    sshfs -o "${SSHFS_OPTS}" "${GUEST_USER}@${HOST}:/" "${MNT}"
  fi
fi

# --- gateway sshd ---
if [ -f "${STATE}/sshd.pid" ] && kill -0 "$(cat "${STATE}/sshd.pid")" 2>/dev/null; then
  echo "Gateway sshd already running (pid $(cat "${STATE}/sshd.pid"))."
else
  rm -f "${STATE}/sshd.pid"
  echo "Starting gateway sshd on 127.0.0.1:${GW_PORT} (user ${HOST_USER})"
  sshd -f "${STATE}/sshd_config" -E "${STATE}/sshd.log"
  sleep 0.4
  if [ ! -f "${STATE}/sshd.pid" ] || ! kill -0 "$(cat "${STATE}/sshd.pid")" 2>/dev/null; then
    echo "error: gateway sshd failed to start. Log:" >&2
    tail -n 40 "${STATE}/sshd.log" >&2 || true
    exit 1
  fi
fi

# Ensure ~/.ssh/config Includes our snippet (idempotent).
mkdir -p "${HOME}/.ssh"
chmod 700 "${HOME}/.ssh"
CFG="${HOME}/.ssh/config"
INC="Include ${STATE}/ssh_config"
touch "${CFG}"
chmod 600 "${CFG}"
if ! grep -F "${INC}" "${CFG}" >/dev/null 2>&1; then
  tmp="$(mktemp)"
  printf '%s\n\n' "${INC}" | cat - "${CFG}" > "${tmp}"
  mv "${tmp}" "${CFG}"
  chmod 600 "${CFG}"
  echo "Prepended to ${CFG}:"
  echo "  ${INC}"
fi

echo ""
echo "AJOS Cursor remote gateway is up."
echo ""
echo "  Guest SSH:    ${GUEST_USER}@${HOST}:${GUEST_PORT}  (password: ${GUEST_PASS})"
echo "  sshfs mount:  ${MNT}"
echo "  Gateway SSH:  ${HOST_USER}@127.0.0.1:${GW_PORT}  (Host ajos)"
echo ""
echo "In Cursor: Command Palette → \"Remote-SSH: Connect to Host\" → ajos"
echo "Then Open Folder:"
echo "  ${MNT}"
echo "or Open Workspace from File:"
echo "  ${STATE}/ajos.code-workspace"
if command -v cursor >/dev/null 2>&1; then
  echo ""
  echo "Or from a terminal on this machine:"
  echo "  cursor --folder-uri \"vscode-remote://ssh-remote+ajos${MNT}\""
fi
echo ""
echo "Stop with:  make cursor-remote-stop"
echo "  or        ${SCRIPT_DIR}/stop.sh"
echo ""
echo "From another computer: SSH to this laptop, then use Host ajos as usual"
echo "(or tunnel ${GW_PORT} and ${GUEST_PORT}). See docs/CURSOR_REMOTE.md."
echo ""
echo "Repo: ${REPO_ROOT}"
