#!/usr/bin/env python3
"""Generate include/font16_aa.h by rasterizing a real UI font into 16x16
cells (4-bit coverage, nibble-packed — keeps the kernel under the 0xA0000
boot-staging ceiling).

Uses the bundled Inter (fonts/Inter.ttf, SIL OFL — see INTER-LICENSE.txt),
weight Medium, size 13, baseline 13 (fits ascenders and descenders in the
cell). Falls back to system Helvetica if the file is missing.
"""
from PIL import Image, ImageDraw, ImageFont
import os

INTER = "fonts/Inter.ttf"
HELV = "/System/Library/Fonts/Helvetica.ttc"

def load_font():
    if os.path.exists(INTER):
        f = ImageFont.truetype(INTER, 13)
        try:
            f.set_variation_by_name("Medium")
        except Exception:
            pass
        return f, 13
    return ImageFont.truetype(HELV, 14, index=0), 12

def main():
    font, baseline = load_font()
    glyphs = []
    for ch in [chr(c) for c in range(32, 127)]:
        img = Image.new("L", (16, 16), 0)
        d = ImageDraw.Draw(img)
        bbox = d.textbbox((0, baseline), ch, font=font, anchor="ls")
        x = (16 - (bbox[2] - bbox[0])) // 2 - bbox[0]
        d.text((x, baseline), ch, font=font, fill=255,
               stroke_width=1, stroke_fill=255, anchor="ls")
        lv = []
        for p in img.getdata():
            l = round(p / 255 * 15)
            if l > 12: l = 15
            elif l < 3: l = 0
            lv.append(l)
        glyphs.append(lv)
    out = ["/* Auto-generated by tools/gen_font16.py: bundled Inter (SIL OFL)\n"
           " rasterized to 16x16 cells, 4-bit coverage, nibble-packed. */\n"
           "#ifndef FONT16_AA_H\n#define FONT16_AA_H\n"
           "static const uint8_t font16_aa[95][128] = {\n"]
    for gi, lv in enumerate(glyphs):
        packed = [(lv[i] << 4) | lv[i + 1] for i in range(0, 256, 2)]
        out.append("{" + ",".join(map(str, packed)) + "}," +
                   ("\n" if gi % 6 == 5 else ""))
    out.append("};\n#endif\n")
    open("include/font16_aa.h", "w").write("".join(out))
    print("include/font16_aa.h regenerated")

if __name__ == "__main__":
    main()
