#!/usr/bin/env python3
"""Regenerate include/font16_aa.h (nibble-packed anti-aliased 16x16 UI
font) from the 8x8 bitmap table in src/video.c. Keep the output small:
the bootloader stages the kernel below 0xA0000 (max ~324KB)."""
import re
src = open("src/video.c").read()
m = re.search(r"font8x8\[95\]\[8\] = \{(.*?)\n\};", src, re.S)
rows = re.findall(r"\{([^}]*)\}", m.group(1))
font = [[int(v, 0) for v in r.split(",")[:8]] for r in rows]
def sample(g, fx, fy):
    x0, y0 = int(fx), int(fy)
    tx, ty = fx - x0, fy - y0
    def px(x, y):
        return ((g[y] >> (7 - x)) & 1) if 0 <= x < 8 and 0 <= y < 8 else 0
    return (px(x0,y0)*(1-tx)*(1-ty) + px(x0+1,y0)*tx*(1-ty) +
            px(x0,y0+1)*(1-tx)*ty + px(x0+1,y0+1)*tx*ty)
out = ["/* Auto-generated by tools/gen_font16.py (nibble-packed: two 0-15\n"
       " coverage levels per byte, high nibble first). Regenerate with\n"
       " `python3 tools/gen_font16.py`. */\n"
       "#ifndef FONT16_AA_H\n#define FONT16_AA_H\n"
       "static const uint8_t font16_aa[95][128] = {\n"]
for gi, g in enumerate(font):
    lv = []
    for y in range(16):
        for x in range(16):
            l = max(0, min(15, int(round(sample(g, x/2.0-0.25, y/2.0-0.25)*15))))
            if l > 11: l = 15
            elif l < 4: l = 0
            lv.append(l)
    packed = [ (lv[i]<<4) | lv[i+1] for i in range(0,256,2) ]
    out.append("{" + ",".join(map(str, packed)) + "}," + ("\n" if gi % 6 == 5 else ""))
out.append("};\n#endif\n")
open("include/font16_aa.h","w").write("".join(out))
print("include/font16_aa.h regenerated")
