#!/usr/bin/env python3
"""Generate include/font16_aa.h by rendering real system fonts (macOS
Helvetica + Menlo) into a 16x16 cell per ASCII char, 4-bit coverage levels,
nibble-packed. Keeps the kernel under the 0xA0000 boot-staging ceiling.

Layout per 16x16 cell: baseline at y=13, glyph horizontally centered
(fixed 16px advance keeps all existing UI metrics).
"""
from PIL import Image, ImageDraw, ImageFont
import sys

HELV = "/System/Library/Fonts/Helvetica.ttc"
MENLO = "/System/Library/Fonts/Menlo.ttc"

def render_set(font_path, size, baseline, monitor_paths=None):
    chars = [chr(c) for c in range(32, 127)]
    glyphs = []
    for ch in chars:
        # Try monitor-specific path first if requested (none for now)
        img = Image.new("L", (16, 16), 0)
        d = ImageDraw.Draw(img)
        f = ImageFont.truetype(font_path, size, index=0)
        try:
            bbox = d.textbbox((0, 0), ch, font=f)
            w = bbox[2] - bbox[0]
            x = (16 - w) // 2 - bbox[0]
        except Exception:
            x = 1
        d.text((x, baseline), ch, font=f, fill=255)
        px = list(img.getdata())
        lv = []
        for p in px:
            l = round(p / 255 * 15)
            if l > 12: l = 15
            elif l < 3: l = 0
            lv.append(l)
        glyphs.append(lv)
    return glyphs

def pack(glyphs):
    out = ["/* Auto-generated by tools/gen_font16.py: system font rendered\n"
           " to 16x16 cells, 4-bit coverage, nibble-packed. */\n"
           "#ifndef FONT16_AA_H\n#define FONT16_AA_H\n"
           "static const uint8_t font16_aa[95][128] = {\n"]
    for gi, lv in enumerate(glyphs):
        packed = [(lv[i] << 4) | lv[i+1] for i in range(0, 256, 2)]
        out.append("{" + ",".join(map(str, packed)) + "}," + ("\n" if gi % 6 == 5 else ""))
    out.append("};\n#endif\n")
    return "".join(out)

if __name__ == "__main__":
    glyphs = render_set(HELV, 16, 13)
    open("include/font16_aa.h", "w").write(pack(glyphs))
    print("include/font16_aa.h regenerated from Helvetica")
